// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkgomkokczyvftjrbejq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZ29ta29rY3p5dmZ0anJiZWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzMDU3OTQsImV4cCI6MjA0OTg4MTc5NH0.IyXGukdJPtjlE8SvbFbvN2j0G1OsGwH0KXmG81PRuHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);